theme: jekyll-theme-minimal
title: Zedong Liu's homepage
description: Incoming PhD student at ICT, CAS, advised by Dingwen Tao and Guangming Tan.  My research interests lie in  machine learning systems and data compression.
plugins:
  - jekyll-sitemap
